sudo: required
services:
  - docker

before_install:
  - docker build -t lulzsec14/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lulzsec14/react-test npm test

after_success:
  - docker build -t lulzsec14/multi-client ./client
  - docker build -t lulzsec14/multi-nginx ./nginx
  - docker build -t lulzsec14/multi-server ./server
  - docker build -t lulzsec14/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push lulzsec14/multi-client
  - docker push lulzsec14/multi-nginx
  - docker push lulzsec14/multi-server
  - docker push lulzsec14/multi-worker


language: generic
